our_summary1 <-
  list("L-Citrulline" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Trigonelline" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "3-Hydroxyanthranilic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Tryptophan" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "2-Picolinic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Kynurenine" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Anthranilic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "5-Hydroxyindole-3-acetic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "N-Acetyl-5-hydroxytryptamine" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Kynurenic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Indole-3-acetic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Indole-3-propionic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Cortisol" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Androstenedione" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Testosterone" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Progesterone" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Pyruvic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Lactic acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "2-Hydroxyisobutyric acid" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Progesterone" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "" =
         list("min"       = ~ min(disp),
              "median (iqr)"    = ~ median_iqr(disp),
              "max"       = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
  )

